foldersTree = gFld("<b>DVSClasses</b>", "", "")
     insDoc(foldersTree, gLnk("DVS Classes Library", "", "main.html"))
aux1 = insFld(foldersTree, gFld("File List", "", "files.html"))
       insDoc(aux1, gLnk("DVSClasses.h", "", ""))
aux1 = insFld(foldersTree, gFld("Data Structures", "", "annotated.html"))
       insDoc(aux1, gLnk("DVSBadArgumentsException", "", "classDVSBadArgumentsException.html"))
       insDoc(aux1, gLnk("DVSCannotOpenHandleException", "", "classDVSCannotOpenHandleException.html"))
       insDoc(aux1, gLnk("DVSCard", "", "classDVSCard.html"))
       insDoc(aux1, gLnk("DVSCardAlreadyUsedException", "", "classDVSCardAlreadyUsedException.html"))
       insDoc(aux1, gLnk("DVSDriverException", "", "classDVSDriverException.html"))
       insDoc(aux1, gLnk("DVSException", "", "classDVSException.html"))
       insDoc(aux1, gLnk("DVSFIFOEmptyException", "", "classDVSFIFOEmptyException.html"))
       insDoc(aux1, gLnk("DVSFIFOInUseException", "", "classDVSFIFOInUseException.html"))
       insDoc(aux1, gLnk("DVSFIFONotStartedException", "", "classDVSFIFONotStartedException.html"))
       insDoc(aux1, gLnk("DVSHandle", "", "classDVSHandle.html"))
       insDoc(aux1, gLnk("DVSInternalErrorException", "", "classDVSInternalErrorException.html"))
       insDoc(aux1, gLnk("DVSNullHandleException", "", "classDVSNullHandleException.html"))
       insDoc(aux1, gLnk("DVSTC", "", "classDVSTC.html"))
aux1 = insFld(foldersTree, gFld("Class Hierarchy", "", "hierarchy.html"))
       insDoc(aux1, gLnk("DVSCard", "", "classDVSCard.html"))
       insDoc(aux1, gLnk("DVSHandle", "", "classDVSHandle.html"))
       insDoc(aux1, gLnk("DVSTC", "", "classDVSTC.html"))
  aux2 = insFld(aux1, gFld("std::exception", "", ""))
    aux3 = insFld(aux2, gFld("DVSException", "", "classDVSException.html"))
           insDoc(aux3, gLnk("DVSBadArgumentsException", "", "classDVSBadArgumentsException.html"))
           insDoc(aux3, gLnk("DVSCannotOpenHandleException", "", "classDVSCannotOpenHandleException.html"))
           insDoc(aux3, gLnk("DVSCardAlreadyUsedException", "", "classDVSCardAlreadyUsedException.html"))
           insDoc(aux3, gLnk("DVSDriverException", "", "classDVSDriverException.html"))
           insDoc(aux3, gLnk("DVSFIFOEmptyException", "", "classDVSFIFOEmptyException.html"))
           insDoc(aux3, gLnk("DVSFIFOInUseException", "", "classDVSFIFOInUseException.html"))
           insDoc(aux3, gLnk("DVSFIFONotStartedException", "", "classDVSFIFONotStartedException.html"))
           insDoc(aux3, gLnk("DVSInternalErrorException", "", "classDVSInternalErrorException.html"))
           insDoc(aux3, gLnk("DVSNullHandleException", "", "classDVSNullHandleException.html"))
     insDoc(foldersTree, gLnk("Data Fields", "", "functions.html"))
